// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAieSLoYv_Yb4xNQR6mkj7EFfcaZFpCqok',
    appId: '1:1057187136884:web:075465517b572b87811821',
    messagingSenderId: '1057187136884',
    projectId: 'instagram-2ad5f',
    authDomain: 'instagram-2ad5f.firebaseapp.com',
    storageBucket: 'instagram-2ad5f.appspot.com',
    measurementId: 'G-S6NYZGXBZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCevWpE46ICKxTlHNyfIduf5e8KirqAUT0',
    appId: '1:1057187136884:android:c9b8c9645836f8b2811821',
    messagingSenderId: '1057187136884',
    projectId: 'instagram-2ad5f',
    storageBucket: 'instagram-2ad5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuyXhcwnqNL8HXy0Eoa5WiTnkRAFY8O48',
    appId: '1:1057187136884:ios:aa08acbeacec9b35811821',
    messagingSenderId: '1057187136884',
    projectId: 'instagram-2ad5f',
    storageBucket: 'instagram-2ad5f.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuyXhcwnqNL8HXy0Eoa5WiTnkRAFY8O48',
    appId: '1:1057187136884:ios:a85d7c541a67b410811821',
    messagingSenderId: '1057187136884',
    projectId: 'instagram-2ad5f',
    storageBucket: 'instagram-2ad5f.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
